// Pre-generated TTS playback (Phase 8). Replaces the Web Speech API speak()
// with HTML5 <audio> playing MP3s generated by `npm run generate-audio`.
//
// Files live in /public/audio/ named name_NN.mp3 and example_NN.mp3 where NN
// is the 2-digit idiom id (matching the IDIOMS array).

let _current = null;

function isMuted() {
  try { return localStorage.getItem("az-idioms-muted") === "1"; } catch (_) { return false; }
}

export function cancelAudio() {
  if (_current) {
    try {
      _current.pause();
      _current.currentTime = 0;
    } catch (_) { /* ignore */ }
    _current = null;
  }
  // Also cancel any in-flight Web Speech utterance so MP3 and TTS never overlap.
  if (typeof window !== "undefined" && "speechSynthesis" in window) {
    try { window.speechSynthesis.cancel(); } catch (_) { /* ignore */ }
  }
}

export function playAudio(filename) {
  cancelAudio();
  if (isMuted()) return;
  try {
    const a = new Audio(`/audio/${filename}`);
    // Autoplay policies sometimes reject — swallow the rejection so callers
    // don't have to handle it (the file just won't play, mute path equivalent).
    a.play().catch(() => { /* ignore autoplay/load rejection */ });
    _current = a;
  } catch (e) {
    console.error("playAudio failed", e);
  }
}

// Convenience wrapper: derive filename from an idiom's id and the kind we want.
//   playForIdiom(idiom)            → name_NN.mp3
//   playForIdiom(idiom, "example") → example_NN.mp3
export function playForIdiom(idiom, kind = "name") {
  if (!idiom || idiom.id == null) return;
  const num = String(idiom.id).padStart(2, "0");
  playAudio(`${kind}_${num}.mp3`);
}

// Web Speech fallback for arbitrary text (used for Medium-level meanings,
// which don't have pre-generated MP3s). Cancels any playing audio first.
// Picks an en-GB voice when available; respects the mute toggle.
export function speakText(text, opts = {}) {
  cancelAudio(); // stops MP3 + any prior utterance (cancelAudio cancels both)
  if (isMuted()) return;
  if (typeof window === "undefined") return;
  if (!("speechSynthesis" in window)) return;
  try {
    const utter = new SpeechSynthesisUtterance(text);
    utter.lang = opts.lang || "en-GB";
    utter.rate = opts.rate ?? 0.9;
    utter.pitch = opts.pitch ?? 1;
    const voices = window.speechSynthesis.getVoices();
    const v =
      voices.find((vc) => vc.lang === "en-GB") ||
      voices.find((vc) => vc.lang && vc.lang.startsWith("en-GB")) ||
      voices.find((vc) => vc.lang && vc.lang.startsWith("en"));
    if (v) utter.voice = v;
    window.speechSynthesis.speak(utter);
  } catch (e) {
    console.error("speakText failed", e);
  }
}
